## title: Chorale Harmonie  
description: Bienvenue sur le site du Choeur Kosmopolis de Bruxelles.  
baseurl: ""  
url: https://choeurkosmopolis.github.io/
theme: minima

---

## layout: default  
title: Accueil

## Bienvenue sur le site du Choeur Kosmopolis !

Nous sommes une chorale basée à Bruxelles, passionnée par la musique et les performances en direct.

### Prochains événements

- **Concert de fin d'année** : 20 juin 2026
- **Répétitions** : Tous les lundis à 19h

### Rejoignez-nous !

Contactez-nous pour plus d'informations.
